// comment
export const GET_COMMENTS = "COMMENT/GET_COMMENTS"
export const GET_COMMENT = "COMMENT/GET_COMMENT"
export const CREATE_COMMENT = "COMMENT/CREATE_COMMENT"
export const UPDATE_COMMENT = "COMMENT/UPDATE_COMMENT"
export const DELETE_COMMENT = "COMMENT/DELETE_COMMENT"

// page 
export const GET_PAGENUMBER = "PAGE/GET_PAGENUMBER"